### ISSUE TITLE
WinVista Pearl sounds

### ISSUE THREAD

**Issue by Sergiaws** [ORelio/Sound-Manager-Schemes#1]
Here is the Windows Vista Ultimate Pearl. That soundscheme appears as an optional update if you update Windows Vista Ultimate.

**Comment by ORelio** [comment]
Didn't know about that sound scheme, looks promising! Do you have a copy of it?

**Comment by ORelio** [comment]
Found the Glass and Pearl sound schemes after searching online and added them to the repo. Thanks for pointing that out!
