### ISSUE TITLE
Again I share a bunch of sound schemes, including Classic Windows sound schemes, some schemes created by myself and other sound schemes

### ISSUE THREAD

**Issue by Sergiaws** [ORelio/Sound-Manager-Schemes#3]
Some of these sound schemes lack some sounds, since you didn't implemented a lot of necesary events to make work such schemes as there where shiped in their original Windows. Since noone would like all of these sound schemes, I would suggest to split the sound schemes into categories an maybe update the installer so you could choose your favorite schemes bassed into the categories.

**Comment by ORelio** [comment]
Hi, and thanks for helping out.

Would you please share the should schemes you made, either by attaching them to your message, or by opening a pull request?

Regarding the current download tool, it is pretty basic, and designed so you can go to My Music and pick a theme whenever you want. I lack time to work on it a the moment (making elaborate UIs takes more time that it seems) but making categories is an interesting idea. Note that you can just say No to sound schemes and go download some manually from the repository; or say Yes and delete the files you do not want.

I implemented all the most common sound events, and I'm not sure which one you felt were lacking?

Thanks 🙂

**Comment by Sergiaws** [comment]
I'm missing email notification event, the event when a program is opened, the selection sound event (applied when you select an element of the desktop) and menu related events. That's what I would need to complete these classic Windows sound schemes. For Categories, a good idea could be put the page in an apache server and organize it in folders and subfolders. It could be even easier to download on older Windows if you use plain http, I could contribute with that, I'm very interested in your project.

**Comment by ORelio** [comment]
OK, thanks for elaborating. I'm lacking time at the moment to work on the project so I'll leave the issue open for now.

**Comment by ORelio** [comment]
All requested features have now been implemented as per [SoundManager v3.1.0](https://github.com/ORelio/Sound-Manager/releases/tag/v3.1.0) 🙂
