### ISSUE TITLE
More sound schemes for windows

### ISSUE THREAD

**Issue by MichalSuchy** [ORelio/Sound-Manager-Schemes#7]
Hello. Can you add other sound schemes for Windows, please? I think for example for Windows 95 or 98 and for themes of Windows 98. They are: Baseball, Dangerous Creatures, Inside Your Computer, Jungle, Leonardo Da Vinci, Musica, Mystery, Nature, Robotz, Science, Space, Sports, The 60's USA, The Golden Era, Travel, Underwater, Utopia and Windows 98. Thanks, Michal.

**Comment by ORelio** [comment]
Hi @MichalSuchy,
Some schemes you are mentioning are already available:
https://github.com/ORelio/Sound-Manager-Schemes/tree/master/Windows/Extra
Regarding the missing ones, don't hesitate to share them if you have the files! I don't have them.

**Comment by ORelio** [comment]
Thanks! I'll look into this and add the missing ones into the repository 👍

**Comment by ORelio** [comment]
Hi @MichalSuchy,
Happy new year 2024!
The additional sound schemes are now available under Windows/Extra. Thanks for sharing! 👍
