### ISSUE TITLE
a sound scheme is mislabeled

### ISSUE THREAD

**Issue by asmarly** [ORelio/Sound-Manager-Schemes#9]
the Samsung Theme sound scheme is often mistaken for being in Longhorn, which isn't true. the real name of the scheme is Samsung Theme.

**Comment by ORelio** [comment]
Hi,
Thanks for pointing this out.
After investigating this matter, I renamed the scheme in the repository.
Also took this opportunity to add a few missing sounds related to battery, incoming email and print complete.
